// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/drift.dart'; // GENERATED BY drift_dev, DO NOT MODIFY.

// ignore_for_file: type=lint,unused_import
//
final class Schema2 extends i0.VersionedSchema {
  Schema2({required super.database}) : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    intentions,
    longTermRelations,
    longTermRelationsSourceGroupOrder,
    longTermRelationsRelatedGroupOrder,
    longTermRelationsImmutableIdentity,
    longTermRelationsActiveParticipantsAfterInsert,
    longTermRelationsActiveParticipantsAfterUpdate,
    intentionsArchiveRequiresNoActiveRelations,
    intentionTitlesFts,
    intentionsFtsAfterInsert,
    intentionsFtsAfterUpdateSearchContent,
    intentionsFtsAfterDelete,
    intentionsActiveCreatedAtAscIdAsc,
    intentionsActiveCreatedAtDescIdAsc,
    intentionsActiveUpdatedAtAscIdAsc,
    intentionsActiveUpdatedAtDescIdAsc,
    intentionsArchivedCreatedAtAscIdAsc,
    intentionsArchivedCreatedAtDescIdAsc,
    intentionsArchivedUpdatedAtAscIdAsc,
    intentionsArchivedUpdatedAtDescIdAsc,
    intentionsAllCreatedAtAscIdAsc,
    intentionsAllCreatedAtDescIdAsc,
    intentionsAllUpdatedAtAscIdAsc,
    intentionsAllUpdatedAtDescIdAsc,
  ];
  late final Shape0 intentions = Shape0(
    source: i0.VersionedTable(
      entityName: 'intentions',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 longTermRelations = Shape1(
    source: i0.VersionedTable(
      entityName: 'long_term_relations',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'UNIQUE(source_intention_id, related_intention_id)',
        'CHECK(source_intention_id <> related_intention_id)',
      ],
      columns: [
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index longTermRelationsSourceGroupOrder = i1.Index(
    'long_term_relations_source_group_order',
    'CREATE INDEX long_term_relations_source_group_order ON long_term_relations (source_intention_id, type, is_archived, priority, creation_sequence)',
  );
  final i1.Index longTermRelationsRelatedGroupOrder = i1.Index(
    'long_term_relations_related_group_order',
    'CREATE INDEX long_term_relations_related_group_order ON long_term_relations (related_intention_id, type, is_archived, priority, creation_sequence)',
  );
  final i1.Trigger longTermRelationsImmutableIdentity = i1.Trigger(
    'CREATE TRIGGER long_term_relations_immutable_identity AFTER UPDATE OF creation_sequence, id ON long_term_relations WHEN new.creation_sequence <> old.creation_sequence OR new.id <> old.id BEGIN SELECT RAISE (ABORT, \'long-term relation identity is immutable\');END',
    'long_term_relations_immutable_identity',
  );
  final i1.Trigger longTermRelationsActiveParticipantsAfterInsert = i1.Trigger(
    'CREATE TRIGGER long_term_relations_active_participants_after_insert AFTER INSERT ON long_term_relations WHEN new.is_archived = 0 AND(NOT EXISTS (SELECT 1 FROM intentions WHERE id = new.source_intention_id AND is_archived = 0) OR NOT EXISTS (SELECT 1 FROM intentions WHERE id = new.related_intention_id AND is_archived = 0))BEGIN SELECT RAISE (ABORT, \'active relation requires active intentions\');END',
    'long_term_relations_active_participants_after_insert',
  );
  final i1.Trigger longTermRelationsActiveParticipantsAfterUpdate = i1.Trigger(
    'CREATE TRIGGER long_term_relations_active_participants_after_update AFTER UPDATE OF source_intention_id, related_intention_id, is_archived ON long_term_relations WHEN new.is_archived = 0 AND(NOT EXISTS (SELECT 1 FROM intentions WHERE id = new.source_intention_id AND is_archived = 0) OR NOT EXISTS (SELECT 1 FROM intentions WHERE id = new.related_intention_id AND is_archived = 0))BEGIN SELECT RAISE (ABORT, \'active relation requires active intentions\');END',
    'long_term_relations_active_participants_after_update',
  );
  final i1.Trigger intentionsArchiveRequiresNoActiveRelations = i1.Trigger(
    'CREATE TRIGGER intentions_archive_requires_no_active_relations AFTER UPDATE OF is_archived ON intentions WHEN old.is_archived = 0 AND new.is_archived = 1 AND EXISTS (SELECT 1 FROM long_term_relations WHERE is_archived = 0 AND(source_intention_id = new.id OR related_intention_id = new.id)) BEGIN SELECT RAISE (ABORT, \'active relations must be archived first\');END',
    'intentions_archive_requires_no_active_relations',
  );
  late final Shape2 intentionTitlesFts = Shape2(
    source: i0.VersionedVirtualTable(
      entityName: 'intention_titles_fts',
      moduleAndArgs: 'fts5(title_search_key, content = \'intentions\', content_rowid = \'rowid\', tokenize = \'trigram case_sensitive 0 remove_diacritics 0\')',
      columns: [_column_16],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Trigger intentionsFtsAfterInsert = i1.Trigger(
    'CREATE TRIGGER intentions_fts_after_insert AFTER INSERT ON intentions BEGIN INSERT INTO intention_titles_fts ("rowid", title_search_key) VALUES (new."rowid", new.title_search_key);END',
    'intentions_fts_after_insert',
  );
  final i1.Trigger intentionsFtsAfterUpdateSearchContent = i1.Trigger(
    'CREATE TRIGGER intentions_fts_after_update_search_content AFTER UPDATE ON intentions BEGIN INSERT INTO intention_titles_fts (intention_titles_fts, "rowid", title_search_key) VALUES (\'delete\', old."rowid", old.title_search_key);INSERT INTO intention_titles_fts ("rowid", title_search_key) VALUES (new."rowid", new.title_search_key);END',
    'intentions_fts_after_update_search_content',
  );
  final i1.Trigger intentionsFtsAfterDelete = i1.Trigger(
    'CREATE TRIGGER intentions_fts_after_delete AFTER DELETE ON intentions BEGIN INSERT INTO intention_titles_fts (intention_titles_fts, "rowid", title_search_key) VALUES (\'delete\', old."rowid", old.title_search_key);END',
    'intentions_fts_after_delete',
  );
  final i1.Index intentionsActiveCreatedAtAscIdAsc = i1.Index(
    'intentions_active_created_at_asc_id_asc',
    'CREATE INDEX intentions_active_created_at_asc_id_asc ON intentions (created_at ASC, id ASC) WHERE is_archived = 0',
  );
  final i1.Index intentionsActiveCreatedAtDescIdAsc = i1.Index(
    'intentions_active_created_at_desc_id_asc',
    'CREATE INDEX intentions_active_created_at_desc_id_asc ON intentions (created_at DESC, id ASC) WHERE is_archived = 0',
  );
  final i1.Index intentionsActiveUpdatedAtAscIdAsc = i1.Index(
    'intentions_active_updated_at_asc_id_asc',
    'CREATE INDEX intentions_active_updated_at_asc_id_asc ON intentions (updated_at ASC, id ASC) WHERE is_archived = 0',
  );
  final i1.Index intentionsActiveUpdatedAtDescIdAsc = i1.Index(
    'intentions_active_updated_at_desc_id_asc',
    'CREATE INDEX intentions_active_updated_at_desc_id_asc ON intentions (updated_at DESC, id ASC) WHERE is_archived = 0',
  );
  final i1.Index intentionsArchivedCreatedAtAscIdAsc = i1.Index(
    'intentions_archived_created_at_asc_id_asc',
    'CREATE INDEX intentions_archived_created_at_asc_id_asc ON intentions (created_at ASC, id ASC) WHERE is_archived = 1',
  );
  final i1.Index intentionsArchivedCreatedAtDescIdAsc = i1.Index(
    'intentions_archived_created_at_desc_id_asc',
    'CREATE INDEX intentions_archived_created_at_desc_id_asc ON intentions (created_at DESC, id ASC) WHERE is_archived = 1',
  );
  final i1.Index intentionsArchivedUpdatedAtAscIdAsc = i1.Index(
    'intentions_archived_updated_at_asc_id_asc',
    'CREATE INDEX intentions_archived_updated_at_asc_id_asc ON intentions (updated_at ASC, id ASC) WHERE is_archived = 1',
  );
  final i1.Index intentionsArchivedUpdatedAtDescIdAsc = i1.Index(
    'intentions_archived_updated_at_desc_id_asc',
    'CREATE INDEX intentions_archived_updated_at_desc_id_asc ON intentions (updated_at DESC, id ASC) WHERE is_archived = 1',
  );
  final i1.Index intentionsAllCreatedAtAscIdAsc = i1.Index(
    'intentions_all_created_at_asc_id_asc',
    'CREATE INDEX intentions_all_created_at_asc_id_asc ON intentions (created_at ASC, id ASC)',
  );
  final i1.Index intentionsAllCreatedAtDescIdAsc = i1.Index(
    'intentions_all_created_at_desc_id_asc',
    'CREATE INDEX intentions_all_created_at_desc_id_asc ON intentions (created_at DESC, id ASC)',
  );
  final i1.Index intentionsAllUpdatedAtAscIdAsc = i1.Index(
    'intentions_all_updated_at_asc_id_asc',
    'CREATE INDEX intentions_all_updated_at_asc_id_asc ON intentions (updated_at ASC, id ASC)',
  );
  final i1.Index intentionsAllUpdatedAtDescIdAsc = i1.Index(
    'intentions_all_updated_at_desc_id_asc',
    'CREATE INDEX intentions_all_updated_at_desc_id_asc ON intentions (updated_at DESC, id ASC)',
  );
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get titleSearchKey =>
      columnsByName['title_search_key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get description =>
      columnsByName['description']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get isActionReady =>
      columnsByName['is_action_ready']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get isArchived =>
      columnsByName['is_archived']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_0(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL PRIMARY KEY',
    );
i1.GeneratedColumn<String> _column_1(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'title',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL CHECK (title <> \'\' AND instr(CAST(title AS BLOB), X\'00\') = 0)',
    );
i1.GeneratedColumn<String> _column_2(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'title_search_key',
      aliasedName,
      false,
      generatedAs: i1.GeneratedAs(
        const i1.CustomExpression('doable_title_search_key(title)'),
        true,
      ),
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL GENERATED ALWAYS AS (doable_title_search_key(title)) STORED CHECK (title_search_key <> \'\' AND instr(CAST(title_search_key AS BLOB), X\'00\') = 0)',
    );
i1.GeneratedColumn<String> _column_3(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'description',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'CHECK (description IS NULL OR(instr(CAST(description AS BLOB), X\'00\') = 0 AND length(trim(description, char(9) || char(10) || char(11) || char(12) || char(13) || char(32))) > 0))',
    );
i1.GeneratedColumn<int> _column_4(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'is_action_ready',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NOT NULL DEFAULT FALSE CHECK (is_action_ready IN (0, 1))',
      defaultValue: const i1.CustomExpression('FALSE'),
    );
i1.GeneratedColumn<int> _column_5(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'is_archived',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NOT NULL DEFAULT FALSE CHECK (is_archived IN (0, 1))',
      defaultValue: const i1.CustomExpression('FALSE'),
    );
i1.GeneratedColumn<int> _column_6(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'created_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_7(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'updated_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get creationSequence =>
      columnsByName['creation_sequence']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get sourceIntentionId =>
      columnsByName['source_intention_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get relatedIntentionId =>
      columnsByName['related_intention_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get type =>
      columnsByName['type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get priority =>
      columnsByName['priority']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get description =>
      columnsByName['description']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get isArchived =>
      columnsByName['is_archived']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_8(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'creation_sequence',
      aliasedName,
      false,
      hasAutoIncrement: true,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NOT NULL PRIMARY KEY AUTOINCREMENT CHECK (creation_sequence > 0)',
    );
i1.GeneratedColumn<String> _column_9(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL UNIQUE',
    );
i1.GeneratedColumn<String> _column_10(
  String aliasedName,
) => i1.GeneratedColumn<String>(
  'source_intention_id',
  aliasedName,
  false,
  type: i1.DriftSqlType.string,
  $customConstraints:
      'NOT NULL REFERENCES intentions(id)ON UPDATE RESTRICT ON DELETE RESTRICT',
);
i1.GeneratedColumn<String> _column_11(
  String aliasedName,
) => i1.GeneratedColumn<String>(
  'related_intention_id',
  aliasedName,
  false,
  type: i1.DriftSqlType.string,
  $customConstraints:
      'NOT NULL REFERENCES intentions(id)ON UPDATE RESTRICT ON DELETE RESTRICT',
);
i1.GeneratedColumn<String> _column_12(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'type',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL CHECK (typeof(type) = \'text\' AND type IN (\'need\', \'can\'))',
    );
i1.GeneratedColumn<int> _column_13(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'priority',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL CHECK (typeof(priority) = \'integer\' AND priority BETWEEN 1 AND 4)',
    );
i1.GeneratedColumn<String> _column_14(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'description',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'CHECK (description IS NULL OR(typeof(description) = \'text\' AND instr(CAST(description AS BLOB), X\'00\') = 0))',
    );
i1.GeneratedColumn<int> _column_15(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'is_archived',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT FALSE CHECK (typeof(is_archived) = \'integer\' AND is_archived IN (0, 1))',
      defaultValue: const i1.CustomExpression('FALSE'),
    );

class Shape2 extends i0.VersionedVirtualTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get titleSearchKey =>
      columnsByName['title_search_key']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_16(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'title_search_key',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );

final class Schema3 extends i0.VersionedSchema {
  Schema3({required super.database}) : super(version: 3);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    intentions,
    dailyChoices,
    dailyChoicesDateCreationOrder,
    dailyChoicesSourceDateCreationOrder,
    dailyChoicesSelectedDateCreationOrder,
    dailyChoicesSourceRecent,
    dailyChoicesSelectedRecent,
    dailyChoicesImmutableIdentity,
    longTermRelations,
    dailyChoicePathSteps,
    dailyChoicePathStepsOneRoot,
    dailyChoicePathStepsOneSuccessor,
    dailyChoicePathStepsRelation,
    longTermRelationsProtectDailyChoicePath,
    longTermRelationsSourceGroupOrder,
    longTermRelationsRelatedGroupOrder,
    longTermRelationsImmutableIdentity,
    longTermRelationsActiveParticipantsAfterInsert,
    longTermRelationsActiveParticipantsAfterUpdate,
    intentionsArchiveRequiresNoActiveRelations,
    intentionTitlesFts,
    intentionsFtsAfterInsert,
    intentionsFtsAfterUpdateSearchContent,
    intentionsFtsAfterDelete,
    intentionsActiveCreatedAtAscIdAsc,
    intentionsActiveCreatedAtDescIdAsc,
    intentionsActiveUpdatedAtAscIdAsc,
    intentionsActiveUpdatedAtDescIdAsc,
    intentionsArchivedCreatedAtAscIdAsc,
    intentionsArchivedCreatedAtDescIdAsc,
    intentionsArchivedUpdatedAtAscIdAsc,
    intentionsArchivedUpdatedAtDescIdAsc,
    intentionsAllCreatedAtAscIdAsc,
    intentionsAllCreatedAtDescIdAsc,
    intentionsAllUpdatedAtAscIdAsc,
    intentionsAllUpdatedAtDescIdAsc,
  ];
  late final Shape0 intentions = Shape0(
    source: i0.VersionedTable(
      entityName: 'intentions',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 dailyChoices = Shape3(
    source: i0.VersionedTable(
      entityName: 'daily_choices',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['CHECK(source_intention_id <> selected_intention_id)'],
      columns: [
        _column_8,
        _column_9,
        _column_10,
        _column_17,
        _column_18,
        _column_14,
        _column_19,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index dailyChoicesDateCreationOrder = i1.Index(
    'daily_choices_date_creation_order',
    'CREATE INDEX daily_choices_date_creation_order ON daily_choices (choice_date, creation_sequence)',
  );
  final i1.Index dailyChoicesSourceDateCreationOrder = i1.Index(
    'daily_choices_source_date_creation_order',
    'CREATE INDEX daily_choices_source_date_creation_order ON daily_choices (source_intention_id, choice_date, creation_sequence)',
  );
  final i1.Index dailyChoicesSelectedDateCreationOrder = i1.Index(
    'daily_choices_selected_date_creation_order',
    'CREATE INDEX daily_choices_selected_date_creation_order ON daily_choices (selected_intention_id, choice_date, creation_sequence)',
  );
  final i1.Index dailyChoicesSourceRecent = i1.Index(
    'daily_choices_source_recent',
    'CREATE INDEX daily_choices_source_recent ON daily_choices (source_intention_id, creation_sequence DESC)',
  );
  final i1.Index dailyChoicesSelectedRecent = i1.Index(
    'daily_choices_selected_recent',
    'CREATE INDEX daily_choices_selected_recent ON daily_choices (selected_intention_id, creation_sequence DESC)',
  );
  final i1.Trigger dailyChoicesImmutableIdentity = i1.Trigger(
    'CREATE TRIGGER daily_choices_immutable_identity AFTER UPDATE OF creation_sequence, id ON daily_choices WHEN new.creation_sequence <> old.creation_sequence OR new.id <> old.id BEGIN SELECT RAISE (ABORT, \'daily choice identity is immutable\');END',
    'daily_choices_immutable_identity',
  );
  late final Shape1 longTermRelations = Shape1(
    source: i0.VersionedTable(
      entityName: 'long_term_relations',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'UNIQUE(source_intention_id, related_intention_id)',
        'CHECK(source_intention_id <> related_intention_id)',
      ],
      columns: [
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 dailyChoicePathSteps = Shape4(
    source: i0.VersionedTable(
      entityName: 'daily_choice_path_steps',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'UNIQUE(daily_choice_id, id)',
        'FOREIGN KEY(daily_choice_id, previous_step_id)REFERENCES daily_choice_path_steps(daily_choice_id, id)ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED',
        'CHECK(previous_step_id IS NULL OR previous_step_id <> id)',
      ],
      columns: [_column_0, _column_20, _column_21, _column_22],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index dailyChoicePathStepsOneRoot = i1.Index(
    'daily_choice_path_steps_one_root',
    'CREATE UNIQUE INDEX daily_choice_path_steps_one_root ON daily_choice_path_steps (daily_choice_id) WHERE previous_step_id IS NULL',
  );
  final i1.Index dailyChoicePathStepsOneSuccessor = i1.Index(
    'daily_choice_path_steps_one_successor',
    'CREATE UNIQUE INDEX daily_choice_path_steps_one_successor ON daily_choice_path_steps (daily_choice_id, previous_step_id) WHERE previous_step_id IS NOT NULL',
  );
  final i1.Index dailyChoicePathStepsRelation = i1.Index(
    'daily_choice_path_steps_relation',
    'CREATE INDEX daily_choice_path_steps_relation ON daily_choice_path_steps (long_term_relation_id)',
  );
  final i1.Trigger longTermRelationsProtectDailyChoicePath = i1.Trigger(
    'CREATE TRIGGER long_term_relations_protect_daily_choice_path BEFORE UPDATE OF type, source_intention_id, related_intention_id ON long_term_relations WHEN(new.type <> old.type OR new.source_intention_id <> old.source_intention_id OR new.related_intention_id <> old.related_intention_id)AND EXISTS (SELECT 1 FROM daily_choice_path_steps WHERE long_term_relation_id = old.id) BEGIN SELECT RAISE (ABORT, \'long-term relation is used by a daily choice path\');END',
    'long_term_relations_protect_daily_choice_path',
  );
  final i1.Index longTermRelationsSourceGroupOrder = i1.Index(
    'long_term_relations_source_group_order',
    'CREATE INDEX long_term_relations_source_group_order ON long_term_relations (source_intention_id, type, is_archived, priority, creation_sequence)',
  );
  final i1.Index longTermRelationsRelatedGroupOrder = i1.Index(
    'long_term_relations_related_group_order',
    'CREATE INDEX long_term_relations_related_group_order ON long_term_relations (related_intention_id, type, is_archived, priority, creation_sequence)',
  );
  final i1.Trigger longTermRelationsImmutableIdentity = i1.Trigger(
    'CREATE TRIGGER long_term_relations_immutable_identity AFTER UPDATE OF creation_sequence, id ON long_term_relations WHEN new.creation_sequence <> old.creation_sequence OR new.id <> old.id BEGIN SELECT RAISE (ABORT, \'long-term relation identity is immutable\');END',
    'long_term_relations_immutable_identity',
  );
  final i1.Trigger longTermRelationsActiveParticipantsAfterInsert = i1.Trigger(
    'CREATE TRIGGER long_term_relations_active_participants_after_insert AFTER INSERT ON long_term_relations WHEN new.is_archived = 0 AND(NOT EXISTS (SELECT 1 FROM intentions WHERE id = new.source_intention_id AND is_archived = 0) OR NOT EXISTS (SELECT 1 FROM intentions WHERE id = new.related_intention_id AND is_archived = 0))BEGIN SELECT RAISE (ABORT, \'active relation requires active intentions\');END',
    'long_term_relations_active_participants_after_insert',
  );
  final i1.Trigger longTermRelationsActiveParticipantsAfterUpdate = i1.Trigger(
    'CREATE TRIGGER long_term_relations_active_participants_after_update AFTER UPDATE OF source_intention_id, related_intention_id, is_archived ON long_term_relations WHEN new.is_archived = 0 AND(NOT EXISTS (SELECT 1 FROM intentions WHERE id = new.source_intention_id AND is_archived = 0) OR NOT EXISTS (SELECT 1 FROM intentions WHERE id = new.related_intention_id AND is_archived = 0))BEGIN SELECT RAISE (ABORT, \'active relation requires active intentions\');END',
    'long_term_relations_active_participants_after_update',
  );
  final i1.Trigger intentionsArchiveRequiresNoActiveRelations = i1.Trigger(
    'CREATE TRIGGER intentions_archive_requires_no_active_relations AFTER UPDATE OF is_archived ON intentions WHEN old.is_archived = 0 AND new.is_archived = 1 AND EXISTS (SELECT 1 FROM long_term_relations WHERE is_archived = 0 AND(source_intention_id = new.id OR related_intention_id = new.id)) BEGIN SELECT RAISE (ABORT, \'active relations must be archived first\');END',
    'intentions_archive_requires_no_active_relations',
  );
  late final Shape2 intentionTitlesFts = Shape2(
    source: i0.VersionedVirtualTable(
      entityName: 'intention_titles_fts',
      moduleAndArgs: 'fts5(title_search_key, content = \'intentions\', content_rowid = \'rowid\', tokenize = \'trigram case_sensitive 0 remove_diacritics 0\')',
      columns: [_column_16],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Trigger intentionsFtsAfterInsert = i1.Trigger(
    'CREATE TRIGGER intentions_fts_after_insert AFTER INSERT ON intentions BEGIN INSERT INTO intention_titles_fts ("rowid", title_search_key) VALUES (new."rowid", new.title_search_key);END',
    'intentions_fts_after_insert',
  );
  final i1.Trigger intentionsFtsAfterUpdateSearchContent = i1.Trigger(
    'CREATE TRIGGER intentions_fts_after_update_search_content AFTER UPDATE ON intentions BEGIN INSERT INTO intention_titles_fts (intention_titles_fts, "rowid", title_search_key) VALUES (\'delete\', old."rowid", old.title_search_key);INSERT INTO intention_titles_fts ("rowid", title_search_key) VALUES (new."rowid", new.title_search_key);END',
    'intentions_fts_after_update_search_content',
  );
  final i1.Trigger intentionsFtsAfterDelete = i1.Trigger(
    'CREATE TRIGGER intentions_fts_after_delete AFTER DELETE ON intentions BEGIN INSERT INTO intention_titles_fts (intention_titles_fts, "rowid", title_search_key) VALUES (\'delete\', old."rowid", old.title_search_key);END',
    'intentions_fts_after_delete',
  );
  final i1.Index intentionsActiveCreatedAtAscIdAsc = i1.Index(
    'intentions_active_created_at_asc_id_asc',
    'CREATE INDEX intentions_active_created_at_asc_id_asc ON intentions (created_at ASC, id ASC) WHERE is_archived = 0',
  );
  final i1.Index intentionsActiveCreatedAtDescIdAsc = i1.Index(
    'intentions_active_created_at_desc_id_asc',
    'CREATE INDEX intentions_active_created_at_desc_id_asc ON intentions (created_at DESC, id ASC) WHERE is_archived = 0',
  );
  final i1.Index intentionsActiveUpdatedAtAscIdAsc = i1.Index(
    'intentions_active_updated_at_asc_id_asc',
    'CREATE INDEX intentions_active_updated_at_asc_id_asc ON intentions (updated_at ASC, id ASC) WHERE is_archived = 0',
  );
  final i1.Index intentionsActiveUpdatedAtDescIdAsc = i1.Index(
    'intentions_active_updated_at_desc_id_asc',
    'CREATE INDEX intentions_active_updated_at_desc_id_asc ON intentions (updated_at DESC, id ASC) WHERE is_archived = 0',
  );
  final i1.Index intentionsArchivedCreatedAtAscIdAsc = i1.Index(
    'intentions_archived_created_at_asc_id_asc',
    'CREATE INDEX intentions_archived_created_at_asc_id_asc ON intentions (created_at ASC, id ASC) WHERE is_archived = 1',
  );
  final i1.Index intentionsArchivedCreatedAtDescIdAsc = i1.Index(
    'intentions_archived_created_at_desc_id_asc',
    'CREATE INDEX intentions_archived_created_at_desc_id_asc ON intentions (created_at DESC, id ASC) WHERE is_archived = 1',
  );
  final i1.Index intentionsArchivedUpdatedAtAscIdAsc = i1.Index(
    'intentions_archived_updated_at_asc_id_asc',
    'CREATE INDEX intentions_archived_updated_at_asc_id_asc ON intentions (updated_at ASC, id ASC) WHERE is_archived = 1',
  );
  final i1.Index intentionsArchivedUpdatedAtDescIdAsc = i1.Index(
    'intentions_archived_updated_at_desc_id_asc',
    'CREATE INDEX intentions_archived_updated_at_desc_id_asc ON intentions (updated_at DESC, id ASC) WHERE is_archived = 1',
  );
  final i1.Index intentionsAllCreatedAtAscIdAsc = i1.Index(
    'intentions_all_created_at_asc_id_asc',
    'CREATE INDEX intentions_all_created_at_asc_id_asc ON intentions (created_at ASC, id ASC)',
  );
  final i1.Index intentionsAllCreatedAtDescIdAsc = i1.Index(
    'intentions_all_created_at_desc_id_asc',
    'CREATE INDEX intentions_all_created_at_desc_id_asc ON intentions (created_at DESC, id ASC)',
  );
  final i1.Index intentionsAllUpdatedAtAscIdAsc = i1.Index(
    'intentions_all_updated_at_asc_id_asc',
    'CREATE INDEX intentions_all_updated_at_asc_id_asc ON intentions (updated_at ASC, id ASC)',
  );
  final i1.Index intentionsAllUpdatedAtDescIdAsc = i1.Index(
    'intentions_all_updated_at_desc_id_asc',
    'CREATE INDEX intentions_all_updated_at_desc_id_asc ON intentions (updated_at DESC, id ASC)',
  );
}

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get creationSequence =>
      columnsByName['creation_sequence']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get sourceIntentionId =>
      columnsByName['source_intention_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get selectedIntentionId =>
      columnsByName['selected_intention_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get choiceDate =>
      columnsByName['choice_date']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get description =>
      columnsByName['description']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get isCompleted =>
      columnsByName['is_completed']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_17(
  String aliasedName,
) => i1.GeneratedColumn<String>(
  'selected_intention_id',
  aliasedName,
  false,
  type: i1.DriftSqlType.string,
  $customConstraints:
      'NOT NULL REFERENCES intentions(id)ON UPDATE RESTRICT ON DELETE RESTRICT',
);
i1.GeneratedColumn<String> _column_18(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'choice_date',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL CHECK (typeof(choice_date) = \'text\' AND length(choice_date) = 10 AND choice_date GLOB \'[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]\')',
    );
i1.GeneratedColumn<int> _column_19(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'is_completed',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL CHECK (typeof(is_completed) = \'integer\' AND is_completed IN (0, 1))',
    );

class Shape4 extends i0.VersionedTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get dailyChoiceId =>
      columnsByName['daily_choice_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get longTermRelationId =>
      columnsByName['long_term_relation_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get previousStepId =>
      columnsByName['previous_step_id']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_20(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'daily_choice_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL REFERENCES daily_choices(id)ON UPDATE RESTRICT ON DELETE CASCADE',
    );
i1.GeneratedColumn<String> _column_21(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'long_term_relation_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL REFERENCES long_term_relations(id)ON UPDATE RESTRICT ON DELETE RESTRICT',
    );
i1.GeneratedColumn<String> _column_22(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'previous_step_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = Schema2(database: database);
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      case 2:
        final schema = Schema3(database: database);
        final migrator = i1.Migrator(database, schema);
        await from2To3(migrator, schema);
        return 3;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
}) => i0.VersionedSchema.stepByStepHelper(
  step: migrationSteps(from1To2: from1To2, from2To3: from2To3),
);
