targets:
  $default:
    builders:
      drift_dev:
        options:
          sql:
            dialect: sqlite
            options:
              modules:
                - fts5
              known_functions:
                doable_title_search_key: "TEXT (TEXT)"
