[tools]
flutter = "3.47"
"github:microsoft/apm" = "latest"
lefthook = "2"
"npm:@fission-ai/openspec" = "1.10"

[tasks]
prepare = "lefthook install"
start = "flutter run"
doctor = "flutter doctor -v"
fmt = "dart format ."
check = [
    "dart format --output=none --set-exit-if-changed .",
    "flutter analyze",
    "flutter test"
]
check-fast = [
    "dart format --output=none --set-exit-if-changed .",
    "flutter analyze",
    "flutter test --exclude-tags=slow"
]
codegen = [
    "flutter gen-l10n",
    "dart run build_runner build"
]
setup = [
    "cp -R ~/projects/doable/apm_modules ./apm_modules/",
    "apm install --frozen",
    "flutter pub get"
]
